server:
  port: 8080
  ssl.enabled: false

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DEV_DATASOURCE_PORT:5432}/${DEV_DATASOURCE_BASE:postgres}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:admin}
    driverClassName: org.postgresql.Driver
  jpa:
    showSql: true
