server:
  ssl.enabled: false

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DEV_DATASOURCE_PORT:5432}/${DEV_DATASOURCE_BASE:postgres}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:admin}
  jpa:
    showSql: true
    open-in-view: true
jwt:
  secret: ${JWT_SECRET:?BFKv?b7PkFEyv%Y~RXgFc@MqQq0xroJ}
  refreshExpiration: ${REFRESH_EXPIRATION:30m}