server:
  port: 8080

spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DEV_DATASOURCE_PORT:5432}/${DEV_DATASOURCE_BASE:postgres}
    username: ${DATABASE_USER:postgres}
    password: ${DATABASE_PASSWORD:admin}
    driverClassName: org.postgresql.Driver
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.xml
    enabled: true
  jpa:
    showSql: false
    hibernate:
      ddlAuto: none
    properties:
      hibernate:
        jdbc:
          batch_size: ${SPRING_JPA_PROPERTIES_BATCH_SIZE:1000}
          fetch_size: ${SPRING_JPA_PROPERTIES_FETCH_SIZE:1000}
          order_inserts: true
          order_updates: true
    open-in-view: false
jwt:
  secret: ${JWT_SECRET:?BFKv?b7PkFEyv%Y~RXgFc@MqQq0xroJ}
  refreshExpiration: ${REFRESH_EXPIRATION:30m}