server:
  port: 8080

spring:
  application:
    name: demo
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DEV_DATASOURCE_PORT:5432}/${DEV_DATASOURCE_BASE}
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}
    driverClassName: org.postgresql.Driver
  jpa:
    showSql: false
    hibernate:
      ddlAuto: none
    properties:
      hibernate:
        jdbc:
          batch_size: ${SPRING_JPA_PROPERTIES_BATCH_SIZE:1000}
          fetch_size: ${SPRING_JPA_PROPERTIES_FETCH_SIZE:1000}
          order_inserts: true
          order_updates: true
    open-in-view: false